name: Local Minima
description: My personal repository of musings and ideas...
pygments: true
markdown: kramdown

navigation:
- text: Blog
  url: /index.html
  name: index
- text: About
  url: /about/index.html
  name: about
- text: Consulting
  url: https://www.lunamonta.com
  name: consulting
- text: Code
  url: https://github.com/jfarid27
  name: code
